### ISSUE TITLE
Ordinal 343 not found in COREDLL

### ISSUE THREAD

**Issue by dz333n** [dz333n/wcecl#1]
![image](https://user-images.githubusercontent.com/25367511/53287450-e6dd8a00-3784-11e9-8717-42996ddee788.png)
*ordinal 343 is not found in library COREDLL*

corelib.dll throws this error

**Comment by dz333n** [comment]
The problem is somewhere in .def file

**Comment by ghost** [comment]
> The problem is somewhere in .def file

https://discord.gg/u74Pk5e
