### ISSUE TITLE
Feature Request: ARM Emulator

### ISSUE THREAD

**Issue by dz333n** [dz333n/wcecl#16]
Most of CE apps are ARM.

**Comment by mediaexplorer74** [comment]
> Most of CE apps are ARM.

Hi! How are you?
Any progress on CE apps are ARM? Do you have some UWP prototypes of WCECL? =)
Best,
Andrey aka MediaExplorer

**Comment by feel-the-dz3n** [comment]
> > Most of CE apps are ARM.
> 
> Hi! How are you? Any progress on CE apps are ARM? Do you have some UWP prototypes of WCECL? =) Best, Andrey aka MediaExplorer

Glory to Ukraine! I'm good, thanks for asking.
I believe there won't be any further progress on this product since it's almost pointless nowadays.

**Comment by TorutheRedFox** [comment]
SH-4 emulation could possibly allow CE-based Dreamcast games to run natively on Win32 too, which would be an absolutely cursed sight
