### ISSUE TITLE
Wiki Problem https://github.com/dz333n/wcecl/wiki/How-to-run-Windows-CE-Solitare 

### ISSUE THREAD

**Issue by Mrjam22** [dz333n/wcecl#23]
the mega.nz Link to download windows ce Solitare on this [Wiki Page](https://github.com/dz333n/wcecl/wiki/How-to-run-Windows-CE-Solitare) does not work it just says The Folder Link you are trying to access is no longer available

**Comment by dz333n** [comment]
@Mrjam22   thanks for pointing it out! fixed
