### ISSUE TITLE
Create own tool to change subsystem

### ISSUE THREAD

**Issue by dz333n** [dz333n/wcecl#3]

**Comment by dz333n** [comment]
created https://github.com/feel-the-dz3n/wcecl/commit/b3aee9a6a0d8f567c4b52025e188b21c12c69e51

**Comment by ghost** [comment]
> created [b3aee9a](https://github.com/feel-the-dz3n/wcecl/commit/b3aee9a6a0d8f567c4b52025e188b21c12c69e51)

https://discord.gg/u74Pk5e
